### ISSUE TITLE
GUI problems in "Notes and Compensations" screen

### ISSUE THREAD

**Issue by yogev1978** [ScDor/alspam#129]
GUI problems in "Notes and Compensations" screen:

- [x]  In "Notes and Compensations", the word "Compensations" appears twice. One of them should be "Group Claims" if I understand correctly.
- [x] The messages should state the date and time the SPAM was received at user phone, and not just the sender name/phone
- [x] The messages should state the sender name/phone as shown in user phone, and not normalized. Now it shows 559709584, and it should show 0559709584 if that is what I see in my SMS manager.

![image](https://user-images.githubusercontent.com/10349199/96374852-01485080-117e-11eb-925c-f06b384d5936.png)

**Comment by ScDor** [comment]
button labels - fixed

regarding your third point, "not normalized": what was shown (starting with 5 rather than 0) was a bug - showing the number from the server and not from the user's phone. it's now fixed,  I don't mark that checkbox yet because the number is stored in the phone as +97212345678, and this is not very friendly to show. What do you think, sho**uld we show the "prettified" number**, i.e. 0512345678 for the last example, **or the "raw" number**, exactly as saved in the phone SMS database? 

I believe the prettified version would be a better fit.

**Comment by yogev1978** [comment]
@ScDor Prettified number looks better, but what if the sender number is from abroad? It will still have the +NNN before it. Also to let the user find the SMS message easily in the built-in SMS application of the phone, the best way is to show what appears there. So if there it appears with +972, then show it with +972 in the application. And if there it appears with 0, then show it with 0 in the application.

**Comment by ScDor** [comment]
that's trivial, no problem

**Comment by ScDor** [comment]
> @ScDor Prettified number looks better, but what if the sender number is from abroad? It will still have the +NNN before it. Also to let the user find the SMS message easily in the built-in SMS application of the phone, the best way is to show what appears there. So if there it appears with +972, then show it with +972 in the application. And if there it appears with 0, then show it with 0 in the application.

that's trivial, sure

**Comment by yogev1978** [comment]
@ScDor There are still 3 issues with this screen:
- [ ] Contrary to what you wrote, reception time is still not shown - only reception date is shown. I see that there is enough place to show also the time.
- [ ] There should be "-" (minus/hyphen) sign between the Hebrew text and the sender name/number, and also between the Hebrew text and the reception date. Now it's tied to each other, and this doesn't look nice.
- [ ] The phrase "מתארגנת תביעה רלוונטית" should be replaced with "מתארגנת תביעה משותפת". Also, the space should be between the message date and the phrase "מתארגנת תביעה משותפת", and now they are tied, and the space appears to the right of the message date, where it shouldn't appear.

**Comment by ScDor** [comment]
done all of them, soon to be closed with the commit
guess time and more test devices will help us tune the spacing method.

**Comment by yogev1978** [comment]
@ScDor That one is still not good, sorry. Text on the first line (מתארגנת תביעה משותפת) became smaller than text on the second line - it should be back to the same size. The space between message date and message text still isn't present, and instead there is a lot of spaces to the right of message date.

![image](https://user-images.githubusercontent.com/10349199/97488941-9827c080-1967-11eb-940b-e7c5d52c7182.png)
